server.port: 7004
server.error.include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment-service-db?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initializationFailTimeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect